FIRA Robot Football: NativeRouteFinders Namespace Reference
NativeRouteFinders Namespace Reference
All the native route finders.
Classes
class GridSquare
A square in a discretised environment.
struct PositionedObject
An object with position and size.
Enumerations
enum SquareType { Empty = 0, Origin, Obstacle, Destination }
The types of GridSquare available.
Functions
void InitGrid (POINT startPoint, POINT endPoint, SIZE fieldSize, SIZE resolution, SIZE gridSize, GridSquare **grid, int objectClearance, SIZE movingObjectSize, PositionedObject *opponents, int opponentsCount)
Initialises a given grid using the information provided.
unique_ptr< vector< POINT > > ReconstructPath (map< GridSquare *, GridSquare * > *cameFrom, GridSquare *currentSquare)
Reconstructs a path from the given cameFrom information.
float CalculateHeuristic (GridSquare *square, POINT endPoint, bool useSqrt)
Calculates the heuristic score for the given square.
float CalculateLength (POINT startPoint, POINT endPoint, bool useSqrt)
Calculates the length from one point to another.
NATIVEROUTEFINDERS_API HRESULT Init ()
Initialises the Native A* Route Finder.
NATIVEROUTEFINDERS_API HRESULT AStarFindRoute (POINT startPoint, POINT endPoint, SIZE fieldSize, SIZE resolution, SIZE movingObjectSize, int objectClearance, PositionedObject *opponents, int opponentsCount, POINT *routeResult, unsigned int routeResultLength, bool useSqrt)
Finds a route using the A* algorithm.
NATIVEROUTEFINDERS_API HRESULT HashMapAStarFindRoute (POINT startPoint, POINT endPoint, SIZE fieldSize, SIZE resolution, SIZE movingObjectSize, int objectClearance, PositionedObject *opponents, int opponentsCount, POINT *routeResult, unsigned int routeResultLength, bool useSqrt)
Finds a route using the A* algorithm.
POINT PointFromIndex (int index, int width)
Converts an array index to a POINT.
int IndexFromPoint (LONG x, LONG y, LONG width)
Converts a point (x,y) to an array index.
int IndexFromPoint (POINT point, LONG width)
Converts a POINT to an array index.
Detailed Description
Namespace intended to contain all the native route finders.
Enumeration Type Documentation
enum NativeRouteFinders::SquareType
Represents the different types of GridSquare that can exist in an environment.
Enumerator:
Empty
A square containing nothing.
Origin
A square to start a route from.
Obstacle
A square that cannot be passed.
Destination
A square to end a route on.
Definition at line 13 of file GridSquare.h.
Function Documentation
NATIVEROUTEFINDERS_API HRESULT NativeRouteFinders::AStarFindRoute (POINT startPoint, POINT endPoint, SIZE fieldSize, SIZE resolution, SIZE movingObjectSize, int objectClearance, PositionedObject * opponents, int opponentsCount, POINT * routeResult, unsigned int routeResultLength, bool useSqrt)
Parameters:
startPoint The point to start the algorithm from.
endPoint The point to find a route to
fieldSize The size of the field that will be searched.
resolution The size of each square in the field, once it has been discretised
movingObjectSize The size of the object that will follow the route
objectClearance The distance that obstacles must be cleared by
opponents The opponents that act as obstacles
opponentsCount The length of the opponents array
routeResult The route that has been produced by the algorithm (an output parameter)
routeResultLength The length of the routeResult array
useSqrt If false, all distance algorithms skip the square root step of the calculation
Returns:
ERROR_SUCCESS if a route has been found and placed in routeResult
E_INVALIDARG if the specified resultion is 0
E_FAIL if no route has been found
ERROR_INSUFFICIENT_BUFFER if the find route is too long for the given buffer
Bug:
Does not currently detect when the 'neighbouring' squares have actually wrapped onto the next line
Determines a route from startPoint to endPoint using the A* algorithm.
Algorithm taken from aiModernApproach.
Definition at line 57 of file AStarRouteFinder.cpp.
References NativeRouteFinders::GridSquare::HeuristicScore, InitGrid(), NativeRouteFinders::GridSquare::KnownScore, Origin, and NativeRouteFinders::GridSquare::Type.
float NativeRouteFinders::CalculateHeuristic (GridSquare * square, POINT endPoint, bool useSqrt)
Parameters:
square The square to calculate the heuristic for
endPoint The current point to aim for
useSqrt If false, all distance algorithms skip the square root step of the calculation
Calculates the heuristic score for the given square.
Returns:
\(+\infty\) if the square is an obstacle
CalculateLength(square->Location, endPoint, useSqrt) otherwise
Definition at line 402 of file AStarRouteFinder.cpp.
References NativeRouteFinders::GridSquare::Location, Obstacle, and NativeRouteFinders::GridSquare::Type.
float NativeRouteFinders::CalculateLength (POINT startPoint, POINT endPoint, bool useSqrt)
Parameters:
startPoint The point to measure from
endPoint The point to measure to
useSqrt If set to false, skip the square-root step
Calculates the distance from startPoint to endPoint using the Euclidian distance.
Note:
Setting useSqrt to false does not appear to produce any time savings. In fact, some experimentation suggests it takes longer
Returns:
A floating point number representing the distance from startPoint to endPoint
Definition at line 382 of file AStarRouteFinder.cpp.
NATIVEROUTEFINDERS_API HRESULT NativeRouteFinders::HashMapAStarFindRoute (POINT startPoint, POINT endPoint, SIZE fieldSize, SIZE resolution, SIZE movingObjectSize, int objectClearance, PositionedObject * opponents, int opponentsCount, POINT * routeResult, unsigned int routeResultLength, bool useSqrt)
Parameters:
startPoint The point to start the algorithm from.
endPoint The point to find a route to
fieldSize The size of the field that will be searched.
resolution The size of each square in the field, once it has been discretised
movingObjectSize The size of the object that will follow the route
objectClearance The distance that obstacles must be cleared by
opponents The opponents that act as obstacles
opponentsCount The length of the opponents array
routeResult The route that has been produced by the algorithm (an output parameter)
routeResultLength The length of the routeResult array
useSqrt If false, all distance algorithms skip the square root step of the calculation
Returns:
ERROR_SUCCESS if a route has been found and placed in routeResult
E_INVALIDARG if the specified resultion is 0
E_FAIL if no route has been found
ERROR_INSUFFICIENT_BUFFER if the find route is too long for the given buffer
Bug:
Does not currently detect when the 'neighbouring' squares have actually wrapped onto the next line
Determines a route from startPoint to endPoint using the A* algorithm. Uses an unordered_set to store the open and closed sets to speed up searches. Otherwise, the algorithm is identical to AStarFindRoute
Algorithm taken from aiModernApproach.
See also:
AStarFindRoute
Definition at line 205 of file AStarRouteFinder.cpp.
References HashMapAStarFindRoute(), NativeRouteFinders::GridSquare::HeuristicScore, NativeRouteFinders::GridSquare::KnownScore, Origin, and NativeRouteFinders::GridSquare::Type.
Referenced by HashMapAStarFindRoute().
int NativeRouteFinders::IndexFromPoint (LONG x, LONG y, LONG width)
Parameters:
x The x coordinate
y The y coordinate
width The width of the grid
Converts a coordinate into an array index, using the width of the field. Works using the equation:
\(index = x + y \times width \)
Returns:
An int containing the index
Definition at line 35 of file PointUtilities.cpp.
Referenced by InitGrid().
int NativeRouteFinders::IndexFromPoint (POINT point, LONG width)
Parameters:
point The coordinate
width The width of the grid
Converts a coordinate into an array index, using the width of the field. Works using the equation:
\(index = point.x + point.y \times width \)
Returns:
An int containing the index
Definition at line 48 of file PointUtilities.cpp.
NATIVEROUTEFINDERS_API HRESULT NativeRouteFinders::Init ()
This function is used by managed software to initialise the DLL for time-testing processes. It is used to ensure that the late-bound DLL has been loaded, so that the loading time does not register in the time tests.
Returns:
ERROR_SUCCESS under all conditions.
Definition at line 28 of file AStarRouteFinder.cpp.
void NativeRouteFinders::InitGrid (POINT startPoint, POINT endPoint, SIZE fieldSize, SIZE resolution, SIZE gridSize, GridSquare ** grid, int objectClearance, SIZE movingObjectSize, PositionedObject * opponents, int opponentsCount)
Takes the already allocated GridSquare array grid and sets it up for use by AStarFindRoute and HashMapAStarFindRoute.
Uses objectClearance and movingObjectSize to determine the apparent size of the opponents, and marks the squares that contain them as SquareType::Obstacle.
Marks the square that contains endPoint as SquareType::Destination.
Marks the square that contains startPoint as SquareType::Origin.
Works in parallel as far as possible, using the Microsoft Parallel Patterns Library (http://msdn.microsoft.com/en-us/library/dd492418.aspx)
Definition at line 321 of file AStarRouteFinder.cpp.
References Destination, IndexFromPoint(), NativeRouteFinders::GridSquare::Location, Obstacle, Origin, PointFromIndex(), and NativeRouteFinders::GridSquare::Type.
Referenced by AStarFindRoute().
POINT NativeRouteFinders::PointFromIndex (int index, int width)
Parameters:
index The index to convert
width The width of the grid
Converts an array index into a set of coordinates, using the width of the field. Works using equations: \(x = index \mod width \)
\(y = index \div width \)
Returns:
A POINT structure containing x and y as LONGs
Definition at line 17 of file PointUtilities.cpp.
Referenced by InitGrid().
unique_ptr< vector< POINT > > NativeRouteFinders::ReconstructPath (map< GridSquare *, GridSquare * > * cameFrom, GridSquare * currentSquare)
Parameters:
cameFrom The list of 'came from' details produced by the A* algorithm
currentSquare The current square to examine
A recursive algorithm that reconstructs the path that has been produced by the A* algorithm
Algorithm taken from aiModernApproach
Definition at line 415 of file AStarRouteFinder.cpp.
References NativeRouteFinders::GridSquare::Location.